import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })


export async function getServerSideProps(){
  const data = import('/data/data.json');
  
  return{
    props:{
      title: "hello everyone",

    }
  }
}






export default function Home({title}) {
  return (
    <>
      <Head>
        <title>Practice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className='w-[80%] my-2 mx-auto text-center'>
          <a className='px-2 text-md' href='/'>Home</a>
          <a className='px-2 text-md' href='/about-us'>About-us</a>
          <a className='px-2 text-md' href='/events'>Events</a>
        </nav>
      <header className='w-full'>
      </header>
      <main className='my-5 px-3'>
      <a href='/events/london' className='w-full text-leading '>
        <Image/>
        <h2 className='font-bold text-2xl py-2'>{title}</h2>
       
      </a>
      <a href='/events/sanfran' className='w-full text-leading '>
        <img />
        <h2 className='font-bold text-2xl py-2'>Events in San Francisco</h2>
        
      </a>
      <a href='/events/barcelona' className='w-full text-leading '>
        <img />
        <h2 className='font-bold text-2xl py-2'>Events in Barcelona</h2>
      </a>
      </main>
    </>
  )
}

